version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
    depends_on:
      - client

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
